### ISSUE TITLE
Use standard input variant

### ISSUE THREAD

**Issue by federico-ntr** [pagopa/mui-italia#298]
Hello,
I was wondering isn't it better to use the standard variant for every input component (TextField, Select, etc.)?
Personally, I like the outlined version more, but BI inputs have just the bottom border, which is very similar to MUI input fields with `variant: 'standard'`. If the goal is to create a theme which mimics the appearance of Bootstrap Italia I think that should be used.

| Library | Screenshot |
| -------- | ------------|
| Bootstrap Italia | ![bootstrap italia select](https://user-images.githubusercontent.com/35468654/192504081-fcef586f-7dbf-42df-b5b7-d10ae8b3b501.png) |
| mui-italia | ![mui-italia select](https://user-images.githubusercontent.com/35468654/192504268-99fb7d6e-4ea1-4d71-aab7-9881e3dd3aa2.png) |
| mui-italia standard variant | ![mui-italia standard variant select](https://user-images.githubusercontent.com/35468654/192505141-d847fb41-ae13-43f0-9e52-d001bb5aa8be.png) |

As you can see just positioning should be a little fine-tuned, but they already look pretty similar.

**Comment by dmnplb** [comment]
Hi Federico,
MUI Italia is currently used by PagoPA developers to keep a consistent style between the different products and it shouldn't be considered as a direct replacement of Bootstrap Italia (that has [its own React version](https://github.com/italia/design-react-kit)). That said, some components are intentionally designed to look like differently, otherwise we would have stayed with Bootstrap Italia
